name: Build and Deploy Node.js Applications

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.20.2'  # Set this to the node version you need

    - name: Install dependencies and build Express app
      working-directory: ./express
      run: |
        npm install

    - name: Install dependencies and build React app
      working-directory: ./react-app
      run: |
        npm install
        npm run build

    - name: Install PM2
      run: sudo npm install pm2@latest -g

    - name: List directory structure
      run: ls -R $GITHUB_WORKSPACE

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          mkdir -p /root/react-app/express
          mkdir -p /root/react-app/build

          pm2 stop web-app || true  # This fails silently if 'web-app' is not found

          rsync -av --delete $GITHUB_WORKSPACE/express/ /root/react-app/express/
          rsync -av --delete $GITHUB_WORKSPACE/react-app/build/ /root/react-app/build/

          cd /root/react-app
          pm2 start web-app --update-env

